### PR TITLE
Login finished

### PR DESCRIPTION
**Pull request by ajeeshcp**
### Tasks :-
- [x] Login UI 
- [x] Input validation
- [x] Login ( API integration )
- [x] Forgot password email sending with reset password url ( API integration )

### CODE REVIEW

**Comment by Muhammed-Rahif** [comment]
I started working on this.

**Comment by Muhammed-Rahif** [comment]
@ajeeshcp The UI looks awesome... :ribbon:

**Review by Muhammed-Rahif — APPROVED** [review]
**LGTM!**

**Comment by Muhammed-Rahif** [comment]
@ajeeshcp @shamilkotta please add your review soon...

**Comment by Muhammed-Rahif** [comment]
@shamilkotta pending your review.

**Review by shamilkotta — APPROVED** [review]

**Pull request merged**
