### PR TITLE
Explore page

### PR DESCRIPTION
**Pull request by shamilkotta**
Explore page:
- [x] Page layout
- [x] Job card
- [x] Full details modal
- [x] API integration

### CODE REVIEW

**Comment by shamilkotta** [comment]
Almost everything completed
Some polishing works are remaining 
@Muhammed-Rahif  @ajeeshcp Please have look

**Comment by Muhammed-Rahif** [comment]
> Almost everything completed Some polishing works are remaining @Muhammed-Rahif @ajeeshcp Please have look

@shamilkotta is it reviewing now... or after api integration?

**Comment by Muhammed-Rahif** [comment]
Screenshot from 2021-11-07 12-04-32
@shamilkotta :sparkles:

**Comment by shamilkotta** [comment]
> > Almost everything completed Some polishing works are remaining @Muhammed-Rahif @ajeeshcp Please have look
> 
> @shamilkotta is it reviewing now... or after api integration?

I think it's better to review now, 
We've to work on backend to integrate api
I have added dummy data and dummy api call also (commended code on explore content component)

**Comment by Muhammed-Rahif** [comment]
@ajeeshcp @shamilkotta api integration finished.. please take a look!

**Review by ajeeshcp — APPROVED** [review]
Everything works properly let's merge it.

**Review by Muhammed-Rahif — APPROVED** [review]
Merging now.

**Pull request merged**
