### PR TITLE
Proposal form

### PR DESCRIPTION
**Pull request by shamilkotta**
- [x] Proposal form UI
- [x] State management
- [x] API integration

### CODE REVIEW

**Review by Muhammed-Rahif — APPROVED** [review]
LGTM!

**Comment by Muhammed-Rahif** [comment]
@ajeeshcp pls add ur review on this!

**Review by ajeeshcp — APPROVED** [review]
Code looks perfect even though I am not seen the UI .

**Comment by Muhammed-Rahif** [comment]
Let's merge this!

**Pull request merged**
