### PR TITLE
Signup finished

### PR DESCRIPTION
**Pull request by Muhammed-Rahif**
### Tasks :- 
- [x] User type select 
- [x] Email and password validation 
- [x] Confirm account page 
- [x] Update user profile based on user type

### CODE REVIEW

**Comment by Muhammed-Rahif** [comment]
@shamilkotta @ajeeshcp please review this changes as soon as possible.... Front-end is slightly behind when comparing back-end!

**Review by shamilkotta — APPROVED** [review]
Everything working fine :)

**Review by ajeeshcp — APPROVED** [review]
This is looking good & all working  properly

**Comment by Muhammed-Rahif** [comment]
So let's merge this...

**Pull request merged**
